# Generated by Django 4.2.1 on 2023-11-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_detailsform_phone_alter_detailsform_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsform',
            name='address',
            field=models.TextField(),
        ),
    ]
